micronaut:
  application:
    name: yacab
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
datasources:
  default:
    url: jdbc:postgresql://${jasync.client.host}:${jasync.client.port}/${jasync.client.database}
    driverClassName: org.postgresql.Driver
    username: ${jasync.client.username}
    password: ${jasync.client.password}
jasync:
  client:
    port: 5432
    host: localhost
    database: yacab
    username: postgres
    password: postgres
    maxActiveConnections: 5

bot:
  username: yetanothercaptchabot